### ISSUE TITLE
client-server.t fails on latest Rakudo

### ISSUE THREAD

**Issue by AlexDaniel** [tokuhirom/p6-WebSocket#15]
```
1..5
starting server
http server is ready: http://127.0.0.1:15555/ (pid:13835, keepalive: 1)
ready connect
ok 1 - c: ready
ok 2 - s: ready
# Looks like you planned 5 tests, but ran 2
```

Bisectable [points](https://gist.github.com/Whateverable/0f0acba0af518988ddddeb207fd52fae) at [better-sched merge](https://github.com/rakudo/rakudo/commit/61a77e60a7d936415503d8916fcc7546569e9135).

I don't know if it's a bug in rakudo or if this module is doing something unreasonable. Let me know what you think.

**Comment by AlexDaniel** [comment]
One of the things that seems to be wrong:
https://github.com/tokuhirom/p6-WebSocket/blob/615252b37eec15663703f0c40b7976f5316cf7e5/lib/WebSocket/Handle.pm6#L24
The comment says that it returns a Promise, but it doesn't. The socket in question is [IO::Socket::INET](https://docs.perl6.org/type/IO::Socket::INET#(IO::Socket)_method_write), not [IO::Socket::Async](https://docs.perl6.org/type/IO::Socket::Async#method_write).

**Comment by AlexDaniel** [comment]
Another problem: DEBUG [is a constant](https://github.com/tokuhirom/p6-WebSocket/blob/615252b37eec15663703f0c40b7976f5316cf7e5/lib/WebSocket/Client.pm6#L24), so [once precompiled](https://docs.perl6.org/language/traps#Constants_are_Compile_Time) there's no real way to change it. Same issue in [HTTP::Server::Tiny](https://github.com/tokuhirom/p6-HTTP-Server-Tiny/blob/4ecf31d783ff9c043a0b0fb8884e0c5d50f9385a/lib/HTTP/Server/Tiny.pm6#L10) which is used in the test.

**Comment by AlexDaniel** [comment]
More debugging, it never gets anything here: https://github.com/tokuhirom/p6-WebSocket/blob/69f6e3bdfb13f40f7caefc8b6cb2cc55bdd240db/lib/WebSocket/P6W.pm6#L57

[STEP1](https://github.com/tokuhirom/p6-WebSocket/blob/69f6e3bdfb13f40f7caefc8b6cb2cc55bdd240db/t/client-server.t#L77] is indeed sent, I checked with Wireshark.

**Comment by AlexDaniel** [comment]
FWIW, here is a little bit of golfing: https://gist.github.com/AlexDaniel/829728c658977bb833f8138ac736423f.
The code in that gist is for the server only, so run the client from [client-server.t](https://github.com/tokuhirom/p6-WebSocket/blob/master/t/client-server.t) but with server commented out there (to reproduce run the server first and then run the client).

[This](https://gist.github.com/AlexDaniel/829728c658977bb833f8138ac736423f#file-websocket-fallout-golf-p6-L65-L67) is where the problem happens. So basically we're [react-whenever-ing on a IO::Socket::Async](https://github.com/tokuhirom/p6-HTTP-Server-Tiny/blob/eb0234cbdc2fea55f12b1247a45a8c39d340c5c2/lib/HTTP/Server/Tiny.pm6#L513-L514), and inside of that there's [supply block with another whenever](https://gist.github.com/AlexDaniel/829728c658977bb833f8138ac736423f#file-websocket-fallout-golf-p6-L58-L66). It seems like there is some kind of an issue with [affinity worker](https://github.com/rakudo/rakudo/commit/61a77e60a7d936415503d8916fcc7546569e9135#diff-6d7bfa05d538ae828eff330472ec119fR178), and it simply gets stuck.

There was [another similar issue (RT #132287)](https://rt.perl.org/Ticket/Display.html?id=132287) which results in a hang (also bisected to the better-sched merge), but I thought that it's not a big deal because there is a much bigger issue (https://github.com/rakudo/rakudo/issues/1202). Now I'm no longer sure. Maybe these are different issues, maybe not.

**Comment by zoffixznet** [comment]
I golfed the issue to [a small test](https://github.com/perl6/roast/commit/74445ddf8a37ef2d880febf5ccf76a160244f2ea) and committed [a hack](https://github.com/rakudo/rakudo/commit/ce7e5444a2c4aa69c2e4421f02a287241199318e) that makes the golf pass, but doesn't yet fix the issue with the module ('cause it only applies when there's just one AffinityWorker and needs a more proper fix).

Tho I think It's safe to say this particular bug is in Rakudo due to deadlock in AffinityWorkers when they're in this nested supply-in-a-sock type of setup.

**Comment by zoffixznet** [comment]
This is now properly fixed with https://github.com/rakudo/rakudo/commit/59bfa5ab37 and Issue can be closed.

**Comment by AlexDaniel** [comment]
@zoffixznet thanks!
