### ISSUE TITLE
WebSocket::P6SGI versus P6SGI

### ISSUE THREAD

**Issue by zostay** [tokuhirom/p6-WebSocket#2]
What is the relationship between P6SGI is and WebSocket::P6SGI? 

I have been working on a [P6SGI](https://github.com/zostay/P6SGI) standard, but this does not seem to be related to that. Since some folks are going to assume that the P6SGI name is used to associated this with that, I was hoping you could clarify the relationship.

**Comment by tokuhirom** [comment]
Hmm. Which part abuse the P6SGI spec?

**Comment by tokuhirom** [comment]
I renamed the class to PSGI6.pm

**Comment by tokuhirom** [comment]
Document updated.
